BASE:
  # 日志等级
  log_lever: "debug"
  # 扩展名
  log_extension: ".log"


db_1:
  #  链接数据库
  db_host: "rm-bp1mtvx6w7igg28e9.mysql.rds.aliyuncs.com"
  db_user: "shangfu_charge"
  db_password: "2Ote#v5PfoVsQniw"
  db_name: "shangfu_charge"

case: "test_login_1"
url: "https://test-napi.bangdao-tech.com/charging-maintenance-server"
data:
   username: "69965"
   password: "Admin123"
   uuid: "uuid"

email:
  #发送邮件信息
  smtpserver : "smtp.163.com"
  receiver : "zhangyin3306@163.com"
  username : "zhangyin3306@163.com"
  # 授权码有效期180天
  password : "ZAGBUTASIAVXPAEY"
